# Generated by Django 3.2.7 on 2021-12-05 02:19

import UtahPrideCenter.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('user_specified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zoom_link', models.CharField(default=None, max_length=128)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UtahPrideCenter.program')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=32)),
                ('specified_pronouns', models.CharField(blank=True, default='', max_length=32)),
                ('pronouns', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='UtahPrideCenter.pronoun')),
            ],
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UtahPrideCenter.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UtahPrideCenter.user')),
            ],
        ),
        migrations.CreateModel(
            name='JoinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=UtahPrideCenter.models.makeTokenString, editable=False, max_length=36, unique=True)),
                ('link_creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UtahPrideCenter.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UtahPrideCenter.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UtahPrideCenter.user')),
            ],
        ),
    ]
