# Generated by Django 3.2.7 on 2021-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtahPrideCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
